#!/bin/bash

export PLATFORM

ostype() {
  uname
}

os_detect() {
  case "$(ostype)" in
    *'Darwin'*)	PLATFORM='osx'		;;
    *)		PLATFORM='unknown'	;;
  esac
}

is_osx() {
  os_detect
  if [ $PLATFORM = "osx" ]; then
    return 0
  else
    return 1
  fi
}

is_osx

echo $PLATFORM
  
if [ -z "${DOTPATH:-}" ]; then
  DOTPATH=~/.dotfiles; export DOTPATH
fi

dotfiles_download() {
  if [ -d "$DOTPATH" ]; then
    echo "abc"
    exit 1
  fi
  echo "d"
}

dotfiles_download
